export const categoryOptions = [
  // Accommodation
  { value: "Accommodation", label: "Accommodation", group: "Accommodation" },
  { value: "Hotels", label: "Hotels", group: "Accommodation" },
  { value: "Guest House", label: "Guest House", group: "Accommodation" },
  { value: "Resorts", label: "Resorts", group: "Accommodation" },
  { value: "Cottages", label: "Cottages", group: "Accommodation" },
  { value: "Villas", label: "Villas", group: "Accommodation" },
  { value: "Apartments", label: "Apartments", group: "Accommodation" },
  { value: "Rent Houses", label: "Rent Houses", group: "Accommodation" },
  { value: "Motels", label: "Motels", group: "Accommodation" },
  { value: "Camping Areas", label: "Camping Areas", group: "Accommodation" },
  { value: "Mountain Huts", label: "Mountain Huts", group: "Accommodation" },
  { value: "Paying Guest", label: "Paying Guest", group: "Accommodation" },
  { value: "Girl's Hostels", label: "Girl's Hostels", group: "Accommodation" },
  { value: "Boy's Hostels", label: "Boy's Hostels", group: "Accommodation" },

  { value: "Restaurants", label: "Restaurants", group: "Food & Beverages" },
  { value: "Cafe", label: "Cafe", group: "Food & Beverages" },
  { value: "Fast Food", label: "Fast Food", group: "Food & Beverages" },
  { value: "Food Street", label: "Food Street", group: "Food & Beverages" },
  { value: "Bakeries", label: "Bakeries", group: "Food & Beverages" },
  { value: "Catering Services", label: "Catering Services", group: "Food & Beverages" },
  { value: "Food Trucks", label: "Food Trucks", group: "Food & Beverages" },
  { value: "Dessert Shops", label: "Dessert Shops", group: "Food & Beverages" },
  { value: "Buffets", label: "Buffets", group: "Food & Beverages" },
  { value: "Fine Dining", label: "Fine Dining", group: "Food & Beverages" },
  { value: "Home Chefs", label: "Home Chefs", group: "Food & Beverages" },
  { value: "Beverages", label: "Beverages", group: "Food & Beverages" },


  // Buyers
  { value: "Luxury Watch Buyers", label: "Luxury Watch Buyers", group: "Buyers" },
  { value: "Old Jewelry Buyers", label: "Old Jewelry Buyers", group: "Buyers" },
  { value: "Car Buyers", label: "Car Buyers", group: "Buyers" },
  { value: "House Buyers", label: "House Buyers", group: "Buyers" },
  { value: "Scrap Buyers", label: "Scrap Buyers", group: "Buyers" },
  { value: "Used Electronics Buyers", label: "Used Electronics Buyers", group: "Buyers" },
  { value: "Furniture Buyers", label: "Furniture Buyers", group: "Buyers" },

  // Marketing & Advertising
  { value: "Advertising", label: "Advertising", group: "Marketing" },
  { value: "Marketing", label: "Marketing", group: "Marketing" },
  { value: "Social Media Marketing", label: "Social Media Marketing", group: "Marketing" },
  { value: "Digital Marketing", label: "Digital Marketing", group: "Marketing" },
  { value: "Social Media Influencers", label: "Social Media Influencers", group: "Marketing" },
  { value: "Content Creators", label: "Content Creators", group: "Marketing" },
  { value: "Bill Boards, Flex & Hoarding", label: "Bill Boards, Flex & Hoarding", group: "Marketing" },
  { value: "Television Advertisement", label: "Television Advertisement", group: "Marketing" },
  { value: "Animations & Graphics", label: "Animations & Graphics", group: "Marketing" },
  { value: "Aerial Advertising", label: "Aerial Advertising", group: "Marketing" },
  { value: "Telemarketing", label: "Telemarketing", group: "Marketing" },
  { value: "Broadcasting", label: "Broadcasting", group: "Marketing" },
  { value: "Video Advertising", label: "Video Advertising", group: "Marketing" },
  { value: "Content Marketing", label: "Content Marketing", group: "Marketing" },
  { value: "Visual Marketing", label: "Visual Marketing", group: "Marketing" },
  { value: "Direct Marketing", label: "Direct Marketing", group: "Marketing" },
  { value: "Media Company", label: "Media Company", group: "Marketing" },
  { value: "Indoor Marketing", label: "Indoor Marketing", group: "Marketing" },
  { value: "Online Advertising", label: "Online Advertising", group: "Marketing" },
  { value: "Outdoor Marketing", label: "Outdoor Marketing", group: "Marketing" },
  { value: "Print Ads", label: "Print Ads", group: "Marketing" },
  { value: "Product Marketing", label: "Product Marketing", group: "Marketing" },
  { value: "Product Placement", label: "Product Placement", group: "Marketing" },
  { value: "Retail Advertising", label: "Retail Advertising", group: "Marketing" },
  { value: "Search Marketing", label: "Search Marketing", group: "Marketing" },

  // Agriculture
  { value: "Live Stocks", label: "Live Stocks", group: "Agriculture" },
  { value: "Pest Control Products", label: "Pest Control Products", group: "Agriculture" },
  { value: "Pest Management Services", label: "Pest Management Services", group: "Agriculture" },
  { value: "Pesticides", label: "Pesticides", group: "Agriculture" },
  { value: "Poultry Farms", label: "Poultry Farms", group: "Agriculture" },
  { value: "Seed Providers", label: "Seed Providers", group: "Agriculture" },
  { value: "Agricultural Aircraft", label: "Agricultural Aircraft", group: "Agriculture" },
  { value: "Vegetable Farming", label: "Vegetable Farming", group: "Agriculture" },
  { value: "Agricultural Machinery", label: "Agricultural Machinery", group: "Agriculture" },
  { value: "Warehouse", label: "Warehouse", group: "Agriculture" },
  { value: "Agricultural Services", label: "Agricultural Services", group: "Agriculture" },
  { value: "Tractor Dealers", label: "Tractor Dealers", group: "Agriculture" },
  { value: "Dairy Farming", label: "Dairy Farming", group: "Agriculture" },
  { value: "Organic Farming", label: "Organic Farming", group: "Agriculture" },
  { value: "Agro Chemicals", label: "Agro Chemicals", group: "Agriculture" },

  // Healthcare
  { value: "Hospitals", label: "Hospitals", group: "Healthcare" },
  { value: "Health Care Center", label: "Health Care Center", group: "Healthcare" },
  { value: "Clinics", label: "Clinics", group: "Healthcare" },
  { value: "Diagnostic Labs", label: "Diagnostic Labs", group: "Healthcare" },
  { value: "Physiotherapy", label: "Physiotherapy", group: "Healthcare" },
  { value: "Mental Health Services", label: "Mental Health Services", group: "Healthcare" },
  { value: "Ambulance Services", label: "Ambulance Services", group: "Healthcare" },
  { value: "Dentists", label: "Dentists", group: "Healthcare" },
  { value: "Eye Clinics", label: "Eye Clinics", group: "Healthcare" },
  { value: "Medical Stores", label: "Medical Stores", group: "Healthcare" },
  { value: "Surgical Equipment Suppliers", label: "Surgical Equipment Suppliers", group: "Healthcare" },
  { value: "Blood Banks", label: "Blood Banks", group: "Healthcare" },
  { value: "Vaccination Centers", label: "Vaccination Centers", group: "Healthcare" },

  // Education
  { value: "Schools", label: "Schools", group: "Education" },
  { value: "Colleges", label: "Colleges", group: "Education" },
  { value: "Universities", label: "Universities", group: "Education" },
  { value: "Coaching Centers", label: "Coaching Centers", group: "Education" },
  { value: "Online Courses", label: "Online Courses", group: "Education" },
  { value: "Language Institutes", label: "Language Institutes", group: "Education" },
  { value: "Technical Institutes", label: "Technical Institutes", group: "Education" },
  { value: "Tutoring Services", label: "Tutoring Services", group: "Education" },
  { value: "Exam Preparation", label: "Exam Preparation", group: "Education" },
  { value: "Computer Training", label: "Computer Training", group: "Education" },
  { value: "Music & Art Schools", label: "Music & Art Schools", group: "Education" },

  // Technology
  { value: "Software Houses", label: "Software Houses", group: "Technology" },
  { value: "IT Services", label: "IT Services", group: "Technology" },
  { value: "Web Development", label: "Web Development", group: "Technology" },
  { value: "App Development", label: "App Development", group: "Technology" },
  { value: "Cyber Security", label: "Cyber Security", group: "Technology" },
  { value: "Tech Support", label: "Tech Support", group: "Technology" },
  { value: "ERP Solutions", label: "ERP Solutions", group: "Technology" },
  { value: "Cloud Services", label: "Cloud Services", group: "Technology" },
  { value: "AI & ML Services", label: "AI & ML Services", group: "Technology" },
  { value: "Freelancers", label: "Freelancers", group: "Technology" },
  { value: "Hardware Suppliers", label: "Hardware Suppliers", group: "Technology" },

  { value: "Plumbing Services", label: "Plumbing Services", group: "Services" },
  { value: "Electricians", label: "Electricians", group: "Services" },
  { value: "Home Cleaning", label: "Home Cleaning", group: "Services" },
  { value: "Legal Services", label: "Legal Services", group: "Services" },
  { value: "Consultants", label: "Consultants", group: "Services" },

  { value: "Supermarkets", label: "Supermarkets", group: "Shopping & Malls" },
  { value: "Clothing Stores", label: "Clothing Stores", group: "Shopping & Malls" },
  { value: "Electronics Shops", label: "Electronics Shops", group: "Shopping & Malls" },
  { value: "Book Stores", label: "Book Stores", group: "Shopping & Malls" },

  { value: "Pharmacies", label: "Pharmacies", group: "Health and Medical" },
  { value: "Physiotherapy", label: "Physiotherapy", group: "Health and Medical" },
  
  { value: "Real Estate Agents", label: "Real Estate Agents", group: "Real Estate Company" },
  { value: "Property Developers", label: "Property Developers", group: "Real Estate Company" },

  { value: "Event Planners", label: "Event Planners", group: "Arts & Entertainment" },
  { value: "Photography Studios", label: "Photography Studios", group: "Arts & Entertainment" },
  { value: "Musicians", label: "Musicians", group: "Arts & Entertainment" },

  { value: "Digital Studios", label: "Digital Studios", group: "Digital Media & IT" },
  { value: "Animation Studios", label: "Animation Studios", group: "Digital Media & IT" },
  { value: "Video Production", label: "Video Production", group: "Digital Media & IT" },

  { value: "Taxi Services", label: "Taxi Services", group: "Transport & Logistics" },
  { value: "Logistics Companies", label: "Logistics Companies", group: "Transport & Logistics" },
  { value: "Courier Services", label: "Courier Services", group: "Transport & Logistics" },

  { value: "Barber Shops", label: "Barber Shops", group: "Beauty & Fitness" },
  { value: "Beauty Salons", label: "Salons", group: "Beauty & Fitness" },
  { value: "Beayty Spas", label: "Spas", group: "Beauty & Fitness" },
  { value: "Gyms", label: "Gyms", group: "Beauty & Fitness" },
  { value: "Fitness Trainers", label: "Fitness Trainers", group: "Beauty & Fitness" },

  { value: "Tour Agencies", label: "Tour Agencies", group: "Tourism & Hospitality" },
  { value: "Travel Agents", label: "Travel Agents", group: "Tourism & Hospitality" },
  { value: "Guided Tours", label: "Guided Tours", group: "Tourism & Hospitality" },
  { value: "Cultural Centers", label: "Cultural Centers", group: "Tourism & Hospitality" },

  { value: "Import Export", label: "Import Export", group: "Businesses & Trades" },
  { value: "Wholesale Dealers", label: "Wholesale Dealers", group: "Businesses & Trades" },
  { value: "Retail Shops", label: "Retail Shops", group: "Businesses & Trades" },
  { value: "Distributors", label: "Distributors", group: "Businesses & Trades" },
  { value: "Traders", label: "Traders", group: "Businesses & Trades" },
  { value: "Manufacturers", label: "Manufacturers", group: "Businesses & Trades" },
  { value: "B2B Services", label: "B2B Services", group: "Businesses & Trades" },
  { value: "Others", label: "Others", group: "Others" }
];
